# pgadmin/docker-compose.yaml
# Based on https://pgsnake.blogspot.com/2019/07/reverse-proxying-to-pgadmin.html

version: "2.1"

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - web
      # - bridge
    environment:
      - PGADMIN_DEFAULT_EMAIL=hh@ii.coop
      - PGADMIN_DEFAULT_PASSWORD=CHANGEME_ADMIN_PASS
    volumes:
      - migrations:/hasura-migrations
    expose:
      - "80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.basic.frontend.rule=Host:pgadmin.sharing.io"
      # to add more ports on the same container
      # - "traefik.admin.port=9443"
      # - "traefik.admin.protocol=https"
      # - "traefik.admin.frontend.rule=Host:admin-hasura.sharing.io"
volumes:
  migrations:
networks:
  # bridge:
  #   external: true
  web:
    external: true
