apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hasura-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Hasura Console'
spec:
  rules:
  - http:
      paths:
      - path: /hasura(/|$)(.*)
        backend:
          serviceName: hasura
          servicePort: 8080
