apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-apisnoop-cncf-io
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hh@ii.coop
    privateKeySecretRef:
      name: letsencrypt-prod-apisnoop-cncf-io
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-prod-apisnoop-cncf-io
spec:
  secretName: letsencrypt-prod-apisnoop-cncf-io
  issuerRef:
    name: letsencrypt-prod-apisnoop-cncf-io
    kind: ClusterIssuer
  dnsNames:
    - apisnoop.cncf.io
