apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tmate
resources:
  - tmate-ns.yaml
  - config.yaml
  - ssh-keys-dev.yaml
  - master.yaml
  - postgres.yaml
  - session.yaml
  - master-ingress.yaml
  - session-ingress.yaml
  - tcp-services.yaml
