steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/snoopdb:$_GIT_TAG',
           '--build-arg', 'IMAGE_ARG=gcr.io/$PROJECT_ID/snoopdb:$_GIT_TAG',
           './postgres']
images:
  - 'gcr.io/$PROJECT_ID/snoopdb:$_GIT_TAG'
options:
  substitution_option: 'ALLOW_LOOSE'
 #experiment, what happens when we don't have substitutions set?
