version: "3.7"

services:
  web:
    image: httpd:2.4-alpine
    restart: always
    networks:
      - web
    volumes:
      - ./:/usr/local/apache2/htdocs/
    expose:
    - "80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.basic.frontend.rule=Host:apisnoop.sharing.io"
networks:
  web:
    external: true
