version: "2.1"

services:
  openapi:
    image: swaggerapi/swagger-ui
    restart: always
    networks:
      - web
      # - bridge
    environment:
      - SWAGGER_JSON=/kubernetes/api/openapi-spec/swagger.json
      - PGADMIN_DEFAULT_PASSWORD=CHANGEME_ADMIN_PASS
    volumes:
      - /zfs/home/hh/go/src/k8s.io/kubernetes:/kubernetes
    expose:
      - "80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"
      - "traefik.basic.frontend.rule=Host:openapi.sharing.io"
      # to add more ports on the same container
      # - "traefik.admin.port=9443"
      # - "traefik.admin.protocol=https"
      # - "traefik.admin.frontend.rule=Host:admin-hasura.sharing.io"
      #volumes:
      # kubernetes:
      #  path: 
networks:
  # bridge:
  #   external: true
  web:
    external: true
