apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configuration.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
# TODO maybe we can use a password generator here?
# TODO set ingress to pgadmin.local.sharing.io 
