# docker-compose.yml

# #+NAME: hasura docker-compose

# hasura/docker-compose.yaml
version: "3.7"

services:
  postgres:
    # image: postgres:11.5 # debian-slim / alternative: postgres:11.5-alpine
    # we need our image to include plpython3u
    build:
      dockerfile: ../postgres/Dockerfile
      context: .
    container_name: "${USER}-postgres"
    shm_size: '64GB' # we currently use big boxes
    restart: always
    networks:
      - db
    environment:
      - POSTGRES_USER=apisnoop
      - POSTGRES_PASSWORD=s3cr3tsauc3
      # - POSTGRES_PASSWORD_FILE="/run/secrets/postgres-passwd" # k8s secret style
      - POSTGRES_DB=apisnoop
      # - POSTGRES_INITDB_ARGS=""
      # - POSTGRES_INITDB_WALDIR=""
      # - PGDATA="/var/lib/postgresql/data/"
      # psql client defaults
      - PGDATABASE=apisnoop
      - PGUSER=apisnoop
    volumes:
      # runs *sql and executable *sh and sources non-executable *sh
      - ./initdb:/docker-entrypoint-initdb.d
      - ./migrations:/migrations
    ports:
      - "$PGPORT:5432"
    # Expose ports without publishing them to the host machine
    # - they’ll only be accessible to linked services.
    expose:
      - "5432"
  pgadmin:
    container_name: "${USER}-pgadmin"
    image: dpage/pgadmin4:4.12
    restart: always
    networks:
      - db
      - web
    environment:
      - PGADMIN_DEFAULT_EMAIL=apisnoop@cncf.io
      - PGADMIN_DEFAULT_PASSWORD=iiapisnoop!!
      # python setup.py --dump-servers /tmp/servers.json --user apisnoop@cncf.io
      - PGADMIN_SERVER_JSON_FILE=/apisnoop/servers.json
      - PGADMIN_CONFIG_APP_NAME=APISnoopQL
      - PGADMIN_CONFIG_APP_COPYRIGHT="Copyright (C) 2019, The Cloud Native Compute Foundation"
      - PGADMIN_CONFIG_LOGIN_BANNER="Welcome to APISnoopQL!"
      - PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD=True
      - PGADMIN_CONFIG_MAX_QUERY_HIST_STORED=1234
      - PGADMIN_CONFIG_SESSION_COOKIE_NAME=apisnoop_session
      - PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED=False
      - PGADMIN_CONFIG_SESSION_EXPIRATION_TIME=7
    volumes:
     - ./pgadmin:/apisnoop
    expose:
      - "80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.basic.frontend.rule=Host:${USER}-pgadmin.sharing.io"
  hasura:
    #image: hasura/graphql-engine:v1.0.0-beta.3
    # append '.cli-migrations' to auto run 'hasura migrations apply'
    container_name: "${USER}-hasura"
    image: hasura/graphql-engine:v1.0.0-beta.5 #.cli-migrations
    restart: always
    networks:
      - web
      - db
    environment:
      # - "HASURA_GRAPHQL_DATABASE_URL=postgres://${USER}@172.17.0.1:5432/${USER}"
      - "HASURA_GRAPHQL_DATABASE_URL=postgres://apisnoop:s3cr3tsauc3@postgres:5432/apisnoop"
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    volumes:
      - ./migrations:/hasura-migrations
    expose:
      - "8080"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"
      - "traefik.basic.frontend.rule=Host:${USER}-hasura.sharing.io"
#volumes:
#  migrations:
networks:
  web:
    external: true
  db:
