---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apisnoop
  namespace: flux-system
spec:
  interval: 24h
  url: https://cncf.github.io/apisnoop
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snoopdb
  namespace: flux-system
spec:
  targetNamespace: default
  releaseName: snoopdb
  storageNamespace: flux-system
  interval: 30m
  chart:
    spec:
      chart: snoopdb
      sourceRef:
        kind: HelmRepository
        name: apisnoop
  # https://github.com/cncf/apisnoop/blob/main/charts/snoopdb/values.yaml
  # values:
  #   image:
  #     repository: gcr.io/k8s-staging-apisnoop/snoopdb
  #     tag: ""
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: auditlogger
  namespace: flux-system
spec:
  targetNamespace: default
  releaseName: auditlogger
  storageNamespace: flux-system
  interval: 30m
  chart:
    spec:
      chart: auditlogger
      sourceRef:
        kind: HelmRepository
        name: apisnoop
  # https://github.com/cncf/apisnoop/blob/main/charts/auditlogger/values.yaml
  # values:
  #   image:
  #     repository: gcr.io/k8s-staging-apisnoop/auditlogger
  #     tag: ""
