apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: pgadmin
  spec:
    selector:
      io.apisnoop.dba: pgadmin
    ports:
    - name: "http"
      port: 80
      targetPort: 80
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pgadmin
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.apisnoop.dba: pgadmin
    template:
      metadata:
        labels:
          io.apisnoop.dba: pgadmin
      spec:
        restartPolicy: Always
        containers:
        - name: pgadmin
          image: "dpage/pgadmin4:4.17"
          ports:
          - containerPort: 80
          env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "apisnoop@ii.coop"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "apisnoopdb"
          - name: PGADMIN_SERVER_JSON_FILE
            value: "/tmp/servers.json"
          - name: PGADMIN_CONFIG_APP_NAME
            value: "\"APISnoopQL\""
          - name: PGADMIN_CONFIG_APP_COPYRIGHT
            value: "\"Copyright 2019 The Cloud Native Compute Foundation\""
          - name: PGADMIN_CONFIG_LOGIN_BANNER
            value: "\"Welcome to APISnoopQL\""
          - name: PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD
            value: "True"
          - name: PGADMIN_CONFIG_MAX_QUERY_HIST_STORED
            value: "1234"
          - name: PGADMIN_CONFIG_SESSION_COOKIE_NAME
            value: "\"apisnoopql_session\""
          - name: PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED
            value: "False"
          - name: PGADMIN_CONFIG_SESSION_EXPIRATION_TIME
            value: "7"
