apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: apisnoop
resources:
  - basic-auth.yaml
  # - namespace.yaml
patchesStategicMerge:
  - hasura-ingress.yaml
  - pgadmin-ingress.yaml
  - tilt-ingress.yaml
