


# #+NAME: traefik.yaml helm values

# kubernetes.io/ingress.class=traefik
# ingressClass = "traefik-internal"
# https://docs.traefik.io/configuration/backends/kubernetes/#ingressendpoint
dashboard:
  enabled: true
  domain: traefik.apisnoop.io
  auth:
    basic:
      admin: "<traefik-admin-password()>"
ssl:
  enabled: true
  enforced: true
  permanentRedirect: true
# service:
#   annotations:
#   labels:
rbac:
  enabled: true
accessLogs:
  enabled: true
  format: json
  fields:
    defaultMode: keep
kubernetes:
  namespaces: [] # all namespaces with empty array
  # namespaces:
    # - apisnoop
    # - default
    # - kube-system
acme:
  enabled: true
  email: hh@ii.coop
  staging: false
  # challengeType: tls-sni-01
  # challengeType: http-01
  # Unable to obtain ACME certificate for domains \"hh-hasura.apisnoop.io\"
  # detected thanks to rule \"Host:hh-hasura.apisnoop.io\" : 
  # unable to generate a certificate for the domains [hh-hasura.apisnoop.io]:
  #  acme: Error -> One or more domains had a problem:\n[hh-hasura.apisnoop.io]
  #  acme: error: 403 :: urn:ietf:params:acme:err or:unauthorized ::
  #  Invalid response from https://hh-hasura.apisnoop.io/.well-known/acme-challenge/2znqGrOWczcTMbLmN5NVm2OwcpQGT_ViPhEoJOpKQb8
  #  [35.189.56.228]: 404, ur l: \n
  challengeType: tls-alpn-01
  # challengeType: dns-01 # Needed for wildcards
  resolvers:
    - 1.1.1.1:53
    - 8.8.8.8:53
  persistence:
    enable: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 1Gi
  # domains:
  #   enabled: false
  #   domainsList:
  #     - main: "*.apisnoop.io"
  #     - sans:
  #       - "traefik.apisnoop.io"
  #       - "hh-apisnoop.apisnoop.io"
  #       - "zz-apisnoop.apisnoop.io"
  # dnsProvider:
  #   # name: dnsimple
  #   dnsimple:
  #     DNSIMPLE_OAUTH_TOKEN: "<dnsimple-auth-token()>"
  #     DNSIMPLE_BASE_URL: "https://api.dnsimple.com/v2/"
