apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - configuration.yaml
  - service-account.yaml
  - tilt-service.yaml
configMapGenerator:
- name: kubemacs-configuration
  behavior: merge
  literals:
  - TZ=Pacific/Auckland
  - GIT_EMAIL=ii@ii.coop
  - GIT_NAME=Hippie Hopper
# configMapGenerator:
#   - name: kubemacs-options
#     env: kubemacs-options
