apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: apisnoop
# resources:
#   - basic-auth.yaml
  # - namespace.yaml
bases:
  - ../local
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1 
      kind: Ingress
      name: pgadmin-ingress
    path: pgadmin-patch.yaml
  - target:
      group: extensions
      version: v1beta1 
      kind: Ingress
      name: hasura-ingress
    path: hasura-patch.yaml
  # uncommend when webapp is enabled in ../local
  # - target:
  #     group: extensions
  #     version: v1beta1 
  #     kind: Ingress
  #     name: webapp-ingress
  #   path: webapp-patch.yaml
configMapGenerator:
- name: kubemacs-configuration
  behavior: merge
  literals:
  - TZ=Pacific/Auckland
  - GIT_EMAIL=caleb@ii.coop
  - GIT_NAME=Caleb Woodbine
images:
  # We should probably move this build into prow / apisnoop
  - name: gcr.io/apisnoop/kubemacs
    newTag: 0.9.24
  # https://console.cloud.google.com/gcr/images/k8s-staging-apisnoop?project=k8s-staging-apisnoop&organizationId=758905017065
  - name: gcr.io/k8s-staging-apisnoop/auditlogger
    newTag: v20200203-0.9.22-30-g8fc1acd
  - name: gcr.io/k8s-staging-apisnoop/hasura
    newTag: v20200203-0.9.22-30-g8fc1acd
  - name: gcr.io/k8s-staging-apisnoop/postgres
    newTag: v20200203-0.9.22-30-g8fc1acd
