apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tilt-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /tilt(/|$)(.*)
        backend:
          serviceName: kubemacs-tilt
          servicePort: 10350
