# Certificate

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-apisnoop
spec:
  secretName: letsencrypt-prod-apisnoop
  issuerRef:
    name: letsencrypt-prod-apisnoop
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "apisnoop.127.0.0.1.xip.io"
    - "pgadmin.127.0.0.1.xip.io"
    - "tilt.127.0.0.1.xip.io"
    - "hasura.127.0.0.1.xip.io"
