# Issuer

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-apisnoop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hostmaster@ii.coop
    privateKeySecretRef:
      name: letsencrypt-prod-apisnoop
    solvers:
      - http01:
          ingress:
            class: nginx
        selector:
          dnsNames:
            - "apisnoop.127.0.0.1.xip.io"
            - "pgadmin.127.0.0.1.xip.io"
            - "tilt.127.0.0.1.xip.io"
            - "hasura.127.0.0.1.xip.io"
