name: Update image

on:
  push:
    branches:
      - "main"

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update the commits!
    steps:
      - uses: actions/checkout@v3
      - name: set sha to var
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short=6 $GITHUB_SHA)" >> $GITHUB_ENV
      - name: test sha var
        run: echo $GITHUB_SHA_SHORT
