name: Update image

on:
  push:
    branches:
      - "main"

jobs:
  update-commits:
    runs-on: ubuntu-latest
    name: Update the commits!
    steps:
      - name: echo test
        run: |
        echo $(git rev-parse --short=6 $GITHUB_SHA)
